export const ActionTypes = {
  SET_BANK: "SET_BANK",
  SET_PRODUCTS: "SET_PRODUCTS",
  SORT_PRODUCTS: "SORT_PRODUCTS",
  SEARCH_PRODUCTS: "SEARCH_PRODUCTS",
  FILTER_PRODUCTS: "FILTER_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
